# =============================================================================
# Trivy Configuration for Salon Booking Frontend
# =============================================================================
# This configuration file customizes Trivy's behavior for container scanning
# =============================================================================

# Severity levels to check
severity:
  - CRITICAL
  - HIGH
  - MEDIUM

# Scan configuration
scan:
  # Skip files larger than 100MB
  skip-files:
    - "**/*.tar.gz"
    - "**/*.zip"
  
  # Directories to skip
  skip-dirs:
    - "node_modules"
    - ".git"
    - "coverage"
    - ".next/cache"

# Vulnerability configuration
vulnerability:
  # Ignore unfixed vulnerabilities
  ignore-unfixed: true
  
  # Vulnerability types to check
  type:
    - os
    - library

# Secret scanning
secret:
  config: ""

# Misconfiguration scanning
misconfiguration:
  # Enable misconfiguration scanning for Dockerfiles
  scanners:
    - dockerfile
